#!/usr/bin/env python3
"""RedAudit Report Decryptor

Usage:
    redaudit_decrypt.py <encrypted_file.(json|txt).enc>

It expects a sibling .salt file generated by RedAudit with the same
base name (e.g. redaudit_20250101_120000.json.enc -> redaudit_20250101_120000.salt).
"""

import sys
import os
import base64
import getpass

from cryptography.fernet import Fernet
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC


def derive_key_from_password(password: str, salt: bytes) -> bytes:
    kdf = PBKDF2HMAC(
        algorithm=hashes.SHA256(),
        length=32,
        salt=salt,
        iterations=480000,
    )
    return base64.urlsafe_b64encode(kdf.derive(password.encode("utf-8")))


def find_salt_file(enc_path: str) -> str | None:
    """Try to infer the name of the salt file from the encrypted file path."""
    candidates: list[str] = []

    if enc_path.endswith(".json.enc"):
        candidates.append(enc_path.replace(".json.enc", ".salt"))
    if enc_path.endswith(".txt.enc"):
        candidates.append(enc_path.replace(".txt.enc", ".salt"))

    # generic fallback: foo.enc -> foo.salt
    if enc_path.endswith(".enc"):
        candidates.append(enc_path[:-4] + ".salt")

    for cand in candidates:
        if os.path.exists(cand):
            return cand

    return None


def decrypt_file(enc_path: str) -> bool:
    if not os.path.exists(enc_path):
        print(f"❌ File not found: {enc_path}")
        return False

    salt_path = find_salt_file(enc_path)
    if not salt_path or not os.path.exists(salt_path):
        print("❌ Salt file not found.")
        print("   Expected a .salt file generated alongside the encrypted report.")
        return False

    try:
        with open(salt_path, "rb") as f:
            salt = f.read()
    except Exception as exc:
        print(f"❌ Failed to read salt file: {exc}")
        return False

    try:
        with open(enc_path, "rb") as f:
            enc_data = f.read()
    except Exception as exc:
        print(f"❌ Failed to read encrypted file: {exc}")
        return False

    password = getpass.getpass("Decryption password: ")
    try:
        key = derive_key_from_password(password, salt)
        fernet = Fernet(key)
        dec_data = fernet.decrypt(enc_data)
    except Exception as exc:
        print(f"❌ Decryption failed: {exc}")
        return False

    out_path = enc_path[:-4] if enc_path.endswith(".enc") else enc_path + ".decrypted"

    if os.path.exists(out_path):
        print(f"⚠️  Output file already exists and will be overwritten: {out_path}")

    try:
        with open(out_path, "wb") as f:
            f.write(dec_data)
    except Exception as exc:
        print(f"❌ Failed to write decrypted file: {exc}")
        return False

    print(f"✓ Decrypted successfully: {out_path}")
    return True


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("Usage: redaudit_decrypt.py <encrypted_file.(json|txt).enc>")
        return 1
    enc_path = argv[1]
    ok = decrypt_file(enc_path)
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))